#!/data/data/com.termux/files/usr/bin/bash

case "$1" in

status)

echo "================================"
echo " STARCORE PLATFORM STATUS"
echo "================================"

cat ~/STARCORE/runtime/platform/health.json

;;

*)
echo "Usage:"
echo " starcore status"
;;

esac
